export const LABELS = {
  DEPARTMENTS: "Departments",
  SEARCH_PLACEHOLDER: "Search departments...",
  STATUS: "Status",
  ALL: "All",
  ACTIVE: "Active",
  INACTIVE: "Inactive",
  COUNT_PREFIX: "Departments: ",
  ADD: "Add",
  NO_DEPARTMENTS: "No departments found",
  LOADING: "Loading...",
  CODE: "Code",
  DESCRIPTION: "Description",
  LOCATION: "Location",
  EMPLOYEES: "Employees",

  ADD_DEPARTMENT: "Add Department",
  EDIT_DEPARTMENT: "Edit Department",
  GOALS: "Goals",
  PROJECTS: "Current Projects",
  STATUS: "Status",
  LOCATION: "Location",
  SAVE: "Save",
  CANCEL: "Cancel",
  REMOVE: "Remove",
  ADD_GOAL: "Add Goal",
  ADD_PROJECT: "Add Project",

  MANAGER: "Manager",
  ASSISTANT_MANAGER: "Assistant Manager",
  LOCATION: "Location",
  BUDGET: "Budget",
  STATUS: "Status",
  ESTABLISHED: "Established",
  SEARCH_EMPLOYEE: "Search Employee by Employee ID",
  CURRENT_PROJECTS: "Current Projects",
  GOALS: "Goals",
  RETRY: "Retry",
};
