export const tableData=[
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "9876543210",
    department: "HR",
    status: "Active",
  },
  {
    id: 2,
    name: "Sam Alt",
    email: "samalt@example.com",
    phone: "9876543211",
    department: "Developer",
    status: "Active",
  },
  {
    id: 3,
    name: "Alice Brown",
    email: "aliceb@example.com",
    phone: "9876543212",
    department: "Finance",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Robert King",
    email: "robertk@example.com",
    phone: "9876543213",
    department: "Marketing",
    status: "Active",
  },
  {
    id: 5,
    name: "Sophia Lee",
    email: "sophial@example.com",
    phone: "9876543214",
    department: "HR",
    status: "Active",
  },
  {
    id: 6,
    name: "Michael Chan",
    email: "michaelc@example.com",
    phone: "9876543215",
    department: "Developer",
    status: "Inactive",
  },
  {
    id: 7,
    name: "Emma Watson",
    email: "emmaw@example.com",
    phone: "9876543216",
    department: "Sales",
    status: "Active",
  },
  {
    id: 8,
    name: "David Green",
    email: "davidg@example.com",
    phone: "9876543217",
    department: "Finance",
    status: "Active",
  },
  {
    id: 9,
    name: "Olivia White",
    email: "oliviaw@example.com",
    phone: "9876543218",
    department: "Marketing",
    status: "Inactive",
  },
  {
    id: 10,
    name: "James Hill",
    email: "jamesh@example.com",
    phone: "9876543219",
    department: "Developer",
    status: "Active",
  },
  // {
  //   id: 11,
  //   name: "Isabella Young",
  //   email: "isabellay@example.com",
  //   phone: "9876543220",
  //   department: "HR",
  //   status: "Active",
  // },
  // {
  //   id: 12,
  //   name: "William Scott",
  //   email: "williams@example.com",
  //   phone: "9876543221",
  //   department: "Sales",
  //   status: "Inactive",
  // },
  // {
  //   id: 13,
  //   name: "Ethan Walker",
  //   email: "ethanw@example.com",
  //   phone: "9876543222",
  //   department: "Finance",
  //   status: "Active",
  // },
  // {
  //   id: 14,
  //   name: "Mia Clark",
  //   email: "miac@example.com",
  //   phone: "9876543223",
  //   department: "Marketing",
  //   status: "Active",
  // },
  // {
  //   id: 15,
  //   name: "Benjamin Lewis",
  //   email: "benjaminl@example.com",
  //   phone: "9876543224",
  //   department: "Developer",
  //   status: "Inactive",
  // },
  // {
  //   id: 16,
  //   name: "Charlotte Adams",
  //   email: "charlottea@example.com",
  //   phone: "9876543225",
  //   department: "Sales",
  //   status: "Active",
  // },
  // {
  //   id: 17,
  //   name: "Daniel Wright",
  //   email: "danielw@example.com",
  //   phone: "9876543226",
  //   department: "HR",
  //   status: "Active",
  // },
  // {
  //   id: 18,
  //   name: "Amelia Turner",
  //   email: "ameliat@example.com",
  //   phone: "9876543227",
  //   department: "Finance",
  //   status: "Inactive",
  // },
  // {
  //   id: 19,
  //   name: "Matthew Harris",
  //   email: "matthewh@example.com",
  //   phone: "9876543228",
  //   department: "Developer",
  //   status: "Active",
  // },
  // {
  //   id: 20,
  //   name: "Harper Nelson",
  //   email: "harpern@example.com",
  //   phone: "9876543229",
  //   department: "Marketing",
  //   status: "Active",
  // }
]
